spring.application.name=Re-EquippedEventFlowEngine
# src/main/resources/application.properties

# Event queue size
eventflow.queue.capacity=5

# Max retries for consumers
eventflow.consumer.max-retries=3

# Number of consumer threads
eventflow.consumer.thread-count=2

# Producer event count
eventflow.producer.event-count=10

# Logging level
logging.level.com.anshika.Re_EquippedEventFlowEngine=INFO

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:eventdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hiberanate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true